steps:
  - name: Your previous build steps
    
  - name: Notify discord
    uses: th0th/notify-discord@v0.4.1
    if: ${{ always() }}
    env:
      DISCORD_WEBHOOK_URL: https://discordapp.com/api/webhooks/1077166308321402981/sBrBUOVVF-e3MmTNofWpIQNohxoj3OrodNJgNMtuPfnV0fj7-6BXqRKc0zcqpyql6G2U
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_JOB_NAME: "Build and deploy"
      GITHUB_JOB_STATUS: ${{ job.status }}