name: discord message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id:  secrets.thomas 
        webhook_token:  secrets.kim
        args: The ${{ github.event_name }} event triggered first step.
        username: "Kim" 
